
export const NOTIFICATION_LOADING = "NOTIFICATION_LOADING";
export const NOTIFICATION_ERROR  = "NOTIFICATION_ERROR";

export const LOAD_MORE_NOTIFICATION = "LOAD_MORE_NOTIFICATION";
export const GET_ALL_NOTIFICATION = 'GET_ALL_NOTIFICATION';

export const GET_ALL_NEW_NOTIFICATION = "GET_ALL_NEW_NOTIFICATION";
export const ADD_NEW_NOTIFICATION = "ADD_NEW_NOTIFICATION";
export const SET_NOTIFICATION_TO_ZERO = "SET_NOTIFICATION_TO_ZERO";