export const GET_ALL_CART = "GET_ALL_CART";
export const ADD_NEW_PRODUCT_VARIANT_TO_CART = "ADD_NEW_PRODUCT_VARIANT_TO_CART";
export const ADD_NEW_PRODUCT_TO_CART = "ADD_NEW_PRODUCT_TO_CART";
export const DELETE_PRODUCT_TO_CART = "DELETE_PRODUCT_TO_CART";
