

export const GET_ALL_FEEDBACK = "GET_ALL_FEEDBACK";
export const GET_ALL_COMMENT_BY_RATING = "GET_ALL_COMMENT_BY_RATING";
export const GET_ALL_COMMNENT ="GET_ALL_COMMNENT";
export const GET_ALL_MEDIA = "GET_ALL_MEDIA";
export const GET_ALL_FEEDBACK_MESSAGE = "GET_ALL_FEEDBACK_MESSAGE";
export const UPDATE_STATUS_SHOW_FEEDBACK_MESSAGE ="UPDATE_STATUS_SHOW_FEEDBACK_MESSAGE";
export const GET_ALL_TOTAL_PAGE = "GET_ALL_TOTAL_PAGE";
export const GET_AVERAGE_RATING = "GET_AVERAGE_RATING";